[psql]
    dbname = "planetdecred"
    host = "localhost"
    user = "postgres"
    pass = "docker"
    sslmode = "disable"
    whitelist=[
        "propagation",
        "block",
        "block_bin",
        "vote",
        "vote_receive_time_deviation"
    ]
